import os

import markdown
import html2text
import re
from flask import Flask
from flask import request
from multi_rake import Rake

app = Flask(__name__)


@app.route("/")
def nada():
    return 'holaa'


@app.route("/keywords", methods=['POST'])
def keywords():
    # entry = {
    #    "text": "La inteligencia artifical es muy interesante. Los elefantes son animales grandes. La ballena es el "
    #            "mamífero más grande del mundo. la jirafa tiene cuello largo. Plutón no es un planeta, "
    #            "Saturno tampoco. Dios es real. Aguante Perón carajo. "

    stopwords = {'a',
                 'á',
                 'acerca',
                 'además',
                 'adonde',
                 'al',
                 'algo',
                 'algún',
                 'alguna',
                 'algunas',
                 'alguno',
                 'algunos',
                 'allende',
                 'ambos',
                 'amén',
                 'ampleamos',
                 'ante',
                 'antes',
                 'aquel',
                 'aquella',
                 'aquellas',
                 'aquellos',
                 'aqui',
                 'arriba',
                 'atras',
                 'aun',
                 'bajo',
                 'bastante',
                 'bien',
                 'cabe',
                 'cabo',
                 'cada',
                 'cierta',
                 'ciertas',
                 'cierto',
                 'ciertos',
                 'circa',
                 'como',
                 'con',
                 'conmigo',
                 'connosco',
                 'conseguimos',
                 'conseguir',
                 'consigo',
                 'consigue',
                 'consiguen',
                 'consigues',
                 'contigo',
                 'contra',
                 'convosco',
                 'convusco',
                 'cual',
                 'cuando',
                 'de',
                 'dejante',
                 'del',
                 'delas',
                 'denominada',
                 'denominadas',
                 'denominado',
                 'denominados',
                 'dentro',
                 'desde',
                 'después',
                 'donde',
                 'dos',
                 'durante',
                 'e',
                 'el',
                 'él',
                 'ella',
                 'ellas',
                 'ellos',
                 'empleais',
                 'emplean',
                 'emplear',
                 'empleas',
                 'empleo',
                 'en',
                 'encima',
                 'entonces',
                 'entre',
                 'era',
                 'erais',
                 'eramos',
                 'éramos',
                 'eran',
                 'erar',
                 'eras',
                 'eres',
                 'es',
                 'esa',
                 'esas',
                 'ese',
                 'eso',
                 'esos',
                 'esta',
                 'está',
                 'estaba',
                 'estabais',
                 'estábamos',
                 'estaban',
                 'estabas',
                 'estad',
                 'estada',
                 'estadas',
                 'estado',
                 'estados',
                 'estais',
                 'estáis',
                 'estamos',
                 'estan',
                 'están',
                 'estando',
                 'estar',
                 'estará',
                 'estarán',
                 'estarás',
                 'estaré',
                 'estaréis',
                 'estaremos',
                 'estaría',
                 'estaríais',
                 'estaríamos',
                 'estarían',
                 'estarías',
                 'estas',
                 'estás',
                 'este',
                 'esté',
                 'estéis',
                 'estemos',
                 'estén',
                 'estés',
                 'esto',
                 'estos',
                 'estoy',
                 'estuve',
                 'estuviera',
                 'estuvierais',
                 'estuviéramos',
                 'estuvieran',
                 'estuvieras',
                 'estuvieron',
                 'estuviese',
                 'estuvieseis',
                 'estuviésemos',
                 'estuviesen',
                 'estuvieses',
                 'estuvimos',
                 'estuviste',
                 'estuvisteis',
                 'estuvo',
                 'excepto',
                 'existente',
                 'existentes',
                 'fin',
                 'fue',
                 'fuera',
                 'fuerais',
                 'fuéramos',
                 'fueran',
                 'fueras',
                 'fueron',
                 'fuerza',
                 'fuese',
                 'fueseis',
                 'fuésemos',
                 'fuesen',
                 'fueses',
                 'fui',
                 'fuimos',
                 'fuiste',
                 'fuisteis',
                 'gueno',
                 'ha',
                 'habéis',
                 'haber',
                 'había',
                 'habíais',
                 'habíamos',
                 'habían',
                 'habías',
                 'habida',
                 'habidas',
                 'habido',
                 'habidos',
                 'habiendo',
                 'habrá',
                 'habrán',
                 'habrás',
                 'habré',
                 'habréis',
                 'habremos',
                 'habría',
                 'habríais',
                 'habríamos',
                 'habrían',
                 'habrías',
                 'hace',
                 'haceis',
                 'hacemos',
                 'hacen',
                 'hacer',
                 'haces',
                 'hacia',
                 'hago',
                 'han',
                 'has',
                 'hasta',
                 'hay',
                 'haya',
                 'hayáis',
                 'hayamos',
                 'hayan',
                 'hayas',
                 'haz',
                 'he',
                 'hemo',
                 'hemos',
                 'hube',
                 'hubiera',
                 'hubierais',
                 'hubiéramos',
                 'hubieran',
                 'hubieras',
                 'hubieron',
                 'hubiese',
                 'hubieseis',
                 'hubiésemos',
                 'hubiesen',
                 'hubieses',
                 'hubimos',
                 'hubiste',
                 'hubisteis',
                 'hubo',
                 'incluso',
                 'intenta',
                 'intentais',
                 'intentamos',
                 'intentan',
                 'intentar',
                 'intentas',
                 'intento',
                 'ir',
                 'la',
                 'largo',
                 'las',
                 'le',
                 'les',
                 'lo',
                 'los',
                 'más',
                 'me',
                 'mediante',
                 'menos',
                 'mi',
                 'mí',
                 'mía',
                 'miar',
                 'mías',
                 'mientras',
                 'mio',
                 'mío',
                 'míos',
                 'mis',
                 'modode',
                 'mucho',
                 'muchos',
                 'muy',
                 'na',
                 'nada',
                 'ni',
                 'no',
                 'nos',
                 'nosotras',
                 'nosotros',
                 'nuestra',
                 'nuestras',
                 'nuestro',
                 'nuestros',
                 'nunca',
                 'o',
                 'os',
                 'otra',
                 'otras',
                 'otro',
                 'otros',
                 'pa',
                 'pa\'',
                 'par',
                 'para',
                 'pero',
                 'poco',
                 'podeis',
                 'podemos',
                 'poder',
                 'podria',
                 'podriais',
                 'podriamos',
                 'podrian',
                 'podrias',
                 'por',
                 'porque',
                 'primero',
                 'pro',
                 'puede',
                 'pueden',
                 'puedo',
                 'pues',
                 'que',
                 'qué',
                 'quien',
                 'quienes',
                 'sabe',
                 'sabeis',
                 'sabemos',
                 'saben',
                 'saber',
                 'sabes',
                 'salvo',
                 'se',
                 'sea',
                 'seáis',
                 'seamos',
                 'sean',
                 'seas',
                 'según',
                 'sentid',
                 'sentida',
                 'sentidas',
                 'sentido',
                 'sentidos',
                 'sentir',
                 'ser',
                 'será',
                 'serán',
                 'serás',
                 'seré',
                 'seréis',
                 'seremos',
                 'sería',
                 'seríais',
                 'seríamos',
                 'serían',
                 'serías',
                 'si',
                 'sí',
                 'sido',
                 'siendo',
                 'siente',
                 'sin',
                 'sintiendo',
                 'so',
                 'sobre',
                 'sois',
                 'solamente',
                 'solo',
                 'somos',
                 'son',
                 'soy',
                 'su',
                 'sus',
                 'suya',
                 'suyas',
                 'suyo',
                 'suyos',
                 'también',
                 'tanto',
                 'te',
                 'tendrá',
                 'tendrán',
                 'tendrás',
                 'tendré',
                 'tendréis',
                 'tendremos',
                 'tendría',
                 'tendríais',
                 'tendríamos',
                 'tendrían',
                 'tendrías',
                 'tened',
                 'teneis',
                 'tenéis',
                 'tenemos',
                 'tener',
                 'tenga',
                 'tengáis',
                 'tengamos',
                 'tengan',
                 'tengas',
                 'tengo',
                 'tenía',
                 'teníais',
                 'teníamos',
                 'tenían',
                 'tenías',
                 'tenida',
                 'tenidas',
                 'tenido',
                 'tenidos',
                 'teniendo',
                 'ti',
                 'tiempo',
                 'tiene',
                 'tienen',
                 'tienes',
                 'todo',
                 'todos',
                 'trabaja',
                 'trabajais',
                 'trabajamos',
                 'trabajan',
                 'trabajar',
                 'trabajas',
                 'trabajo',
                 'tras',
                 'tu',
                 'tú',
                 'tus',
                 'tuve',
                 'tuviera',
                 'tuvierais',
                 'tuviéramos',
                 'tuvieran',
                 'tuvieras',
                 'tuvieron',
                 'tuviese',
                 'tuvieseis',
                 'tuviésemos',
                 'tuviesen',
                 'tuvieses',
                 'tuvimos',
                 'tuviste',
                 'tuvisteis',
                 'tuvo',
                 'tuya',
                 'tuyas',
                 'tuyo',
                 'tuyos',
                 'ultimar',
                 'ultimo',
                 'un',
                 'un',
                 'una',
                 'unas',
                 'uno',
                 'unos',
                 'usa',
                 'usais',
                 'usamos',
                 'usan',
                 'usar',
                 'usas',
                 'utilizando',
                 'uso',
                 'va',
                 'vais',
                 'valor',
                 'vamos',
                 'van',
                 'vaya',
                 'verdad',
                 'verdadera',
                 'verdadero',
                 'versus',
                 'vía',
                 'vosostras',
                 'vosostros',
                 'vosotras',
                 'vosotros',
                 'voy',
                 'vuestra',
                 'vuestras',
                 'vuestro',
                 'vuestros',
                 'vusco',
                 'y',
                 'ya',
                 'yo',
                 'optimizando',
                 'actualmente',
                 'llevar',
                 'manera',
                 'podrán',
                 'reduciendo',
                 'brindar'
    }

    text_es = request.json['text']
    stopwords_list = request.json['stopwords']
    stopwords_list_clean = re.sub('[\[\]]', '', stopwords_list).split(", ")
    stopwords.update(stopwords_list_clean)

    print(stopwords)

    html = markdown.markdown(text_es)
    plain_text = html2text.html2text(html)
    plain_text = re.sub('[!@·•*\[\]/#$]', '', plain_text)
    plain_text = plain_text.replace('\\n', '. ')
    plain_text = re.sub(r'http\S+', '', plain_text, flags=re.MULTILINE)
    plain_text = re.sub(r'www\S+', '', plain_text, flags=re.MULTILINE)

    result = []

    # de 2 palabras
    rake = Rake(
        language_code='es',
        max_words=2,
        generated_stopwords_max_len=20,
        stopwords=stopwords
    )
    key_words_2 = rake.apply(plain_text)
    keys2 = key_words_2[:20]

    for key in keys2:
        item = {
            "name": key[0],
            "score": key[1]
        }
        result.append(item)

    # de 1 palabra
    rake = Rake(
        language_code='es',
        max_words=1,
        generated_stopwords_max_len=20,
        stopwords=stopwords
    )
    key_words_1 = rake.apply(plain_text)
    keys1 = key_words_1[:50]

    for key in keys1:
        if not resultContains(result, key[0]):
            item = {
                "name": key[0],
                "score": key[1]
            }
            if len(result) < 40:
                result.append(item)

    response = {
        "keywords": result
    }

    print(response)

    return response

@app.route("/hashtags", methods=['POST'])
def hashtags():
    # entry = {
    #    "text": "La inteligencia artifical es muy interesante. Los elefantes son animales grandes. La ballena es el "
    #            "mamífero más grande del mundo. la jirafa tiene cuello largo. Plutón no es un planeta, "
    #            "Saturno tampoco. Dios es real. Aguante Perón carajo. "

    stopwords = {'a',
                 'á',
                 'acerca',
                 'además',
                 'adonde',
                 'al',
                 'algo',
                 'algún',
                 'alguna',
                 'algunas',
                 'alguno',
                 'algunos',
                 'allende',
                 'ambos',
                 'amén',
                 'ampleamos',
                 'ante',
                 'antes',
                 'aquel',
                 'aquella',
                 'aquellas',
                 'aquellos',
                 'aqui',
                 'arriba',
                 'atras',
                 'aun',
                 'bajo',
                 'bastante',
                 'bien',
                 'cabe',
                 'cabo',
                 'cada',
                 'cierta',
                 'ciertas',
                 'cierto',
                 'ciertos',
                 'circa',
                 'como',
                 'con',
                 'conmigo',
                 'connosco',
                 'conseguimos',
                 'conseguir',
                 'consigo',
                 'consigue',
                 'consiguen',
                 'consigues',
                 'contigo',
                 'contra',
                 'convosco',
                 'convusco',
                 'cual',
                 'cuando',
                 'de',
                 'dejante',
                 'del',
                 'delas',
                 'denominada',
                 'denominadas',
                 'denominado',
                 'denominados',
                 'dentro',
                 'desde',
                 'después',
                 'donde',
                 'dos',
                 'durante',
                 'e',
                 'el',
                 'él',
                 'ella',
                 'ellas',
                 'ellos',
                 'empleais',
                 'emplean',
                 'emplear',
                 'empleas',
                 'empleo',
                 'en',
                 'encima',
                 'entonces',
                 'entre',
                 'era',
                 'erais',
                 'eramos',
                 'éramos',
                 'eran',
                 'erar',
                 'eras',
                 'eres',
                 'es',
                 'esa',
                 'esas',
                 'ese',
                 'eso',
                 'esos',
                 'esta',
                 'está',
                 'estaba',
                 'estabais',
                 'estábamos',
                 'estaban',
                 'estabas',
                 'estad',
                 'estada',
                 'estadas',
                 'estado',
                 'estados',
                 'estais',
                 'estáis',
                 'estamos',
                 'estan',
                 'están',
                 'estando',
                 'estar',
                 'estará',
                 'estarán',
                 'estarás',
                 'estaré',
                 'estaréis',
                 'estaremos',
                 'estaría',
                 'estaríais',
                 'estaríamos',
                 'estarían',
                 'estarías',
                 'estas',
                 'estás',
                 'este',
                 'esté',
                 'estéis',
                 'estemos',
                 'estén',
                 'estés',
                 'esto',
                 'estos',
                 'estoy',
                 'estuve',
                 'estuviera',
                 'estuvierais',
                 'estuviéramos',
                 'estuvieran',
                 'estuvieras',
                 'estuvieron',
                 'estuviese',
                 'estuvieseis',
                 'estuviésemos',
                 'estuviesen',
                 'estuvieses',
                 'estuvimos',
                 'estuviste',
                 'estuvisteis',
                 'estuvo',
                 'excepto',
                 'existente',
                 'existentes',
                 'fin',
                 'fue',
                 'fuera',
                 'fuerais',
                 'fuéramos',
                 'fueran',
                 'fueras',
                 'fueron',
                 'fuerza',
                 'fuese',
                 'fueseis',
                 'fuésemos',
                 'fuesen',
                 'fueses',
                 'fui',
                 'fuimos',
                 'fuiste',
                 'fuisteis',
                 'gueno',
                 'ha',
                 'habéis',
                 'haber',
                 'había',
                 'habíais',
                 'habíamos',
                 'habían',
                 'habías',
                 'habida',
                 'habidas',
                 'habido',
                 'habidos',
                 'habiendo',
                 'habrá',
                 'habrán',
                 'habrás',
                 'habré',
                 'habréis',
                 'habremos',
                 'habría',
                 'habríais',
                 'habríamos',
                 'habrían',
                 'habrías',
                 'hace',
                 'haceis',
                 'hacemos',
                 'hacen',
                 'hacer',
                 'haces',
                 'hacia',
                 'hago',
                 'han',
                 'has',
                 'hasta',
                 'hay',
                 'haya',
                 'hayáis',
                 'hayamos',
                 'hayan',
                 'hayas',
                 'haz',
                 'he',
                 'hemo',
                 'hemos',
                 'hube',
                 'hubiera',
                 'hubierais',
                 'hubiéramos',
                 'hubieran',
                 'hubieras',
                 'hubieron',
                 'hubiese',
                 'hubieseis',
                 'hubiésemos',
                 'hubiesen',
                 'hubieses',
                 'hubimos',
                 'hubiste',
                 'hubisteis',
                 'hubo',
                 'incluso',
                 'intenta',
                 'intentais',
                 'intentamos',
                 'intentan',
                 'intentar',
                 'intentas',
                 'intento',
                 'ir',
                 'la',
                 'largo',
                 'las',
                 'le',
                 'les',
                 'lo',
                 'los',
                 'más',
                 'me',
                 'mediante',
                 'menos',
                 'mi',
                 'mí',
                 'mía',
                 'miar',
                 'mías',
                 'mientras',
                 'mio',
                 'mío',
                 'míos',
                 'mis',
                 'modode',
                 'mucho',
                 'muchos',
                 'muy',
                 'na',
                 'nada',
                 'ni',
                 'no',
                 'nos',
                 'nosotras',
                 'nosotros',
                 'nuestra',
                 'nuestras',
                 'nuestro',
                 'nuestros',
                 'nunca',
                 'o',
                 'os',
                 'otra',
                 'otras',
                 'otro',
                 'otros',
                 'pa',
                 'pa\'',
                 'par',
                 'para',
                 'pero',
                 'poco',
                 'podeis',
                 'podemos',
                 'poder',
                 'podria',
                 'podriais',
                 'podriamos',
                 'podrian',
                 'podrias',
                 'por',
                 'porque',
                 'primero',
                 'pro',
                 'puede',
                 'pueden',
                 'puedo',
                 'pues',
                 'que',
                 'qué',
                 'quien',
                 'quienes',
                 'sabe',
                 'sabeis',
                 'sabemos',
                 'saben',
                 'saber',
                 'sabes',
                 'salvo',
                 'se',
                 'sea',
                 'seáis',
                 'seamos',
                 'sean',
                 'seas',
                 'según',
                 'sentid',
                 'sentida',
                 'sentidas',
                 'sentido',
                 'sentidos',
                 'sentir',
                 'ser',
                 'será',
                 'serán',
                 'serás',
                 'seré',
                 'seréis',
                 'seremos',
                 'sería',
                 'seríais',
                 'seríamos',
                 'serían',
                 'serías',
                 'si',
                 'sí',
                 'sido',
                 'siendo',
                 'siente',
                 'sin',
                 'sintiendo',
                 'so',
                 'sobre',
                 'sois',
                 'solamente',
                 'solo',
                 'somos',
                 'son',
                 'soy',
                 'su',
                 'sus',
                 'suya',
                 'suyas',
                 'suyo',
                 'suyos',
                 'también',
                 'tanto',
                 'te',
                 'tendrá',
                 'tendrán',
                 'tendrás',
                 'tendré',
                 'tendréis',
                 'tendremos',
                 'tendría',
                 'tendríais',
                 'tendríamos',
                 'tendrían',
                 'tendrías',
                 'tened',
                 'teneis',
                 'tenéis',
                 'tenemos',
                 'tener',
                 'tenga',
                 'tengáis',
                 'tengamos',
                 'tengan',
                 'tengas',
                 'tengo',
                 'tenía',
                 'teníais',
                 'teníamos',
                 'tenían',
                 'tenías',
                 'tenida',
                 'tenidas',
                 'tenido',
                 'tenidos',
                 'teniendo',
                 'ti',
                 'tiempo',
                 'tiene',
                 'tienen',
                 'tienes',
                 'todo',
                 'todos',
                 'trabaja',
                 'trabajais',
                 'trabajamos',
                 'trabajan',
                 'trabajar',
                 'trabajas',
                 'trabajo',
                 'tras',
                 'tu',
                 'tú',
                 'tus',
                 'tuve',
                 'tuviera',
                 'tuvierais',
                 'tuviéramos',
                 'tuvieran',
                 'tuvieras',
                 'tuvieron',
                 'tuviese',
                 'tuvieseis',
                 'tuviésemos',
                 'tuviesen',
                 'tuvieses',
                 'tuvimos',
                 'tuviste',
                 'tuvisteis',
                 'tuvo',
                 'tuya',
                 'tuyas',
                 'tuyo',
                 'tuyos',
                 'ultimar',
                 'ultimo',
                 'un',
                 'un',
                 'una',
                 'unas',
                 'uno',
                 'unos',
                 'usa',
                 'usais',
                 'usamos',
                 'usan',
                 'usar',
                 'usas',
                 'utilizando',
                 'uso',
                 'va',
                 'vais',
                 'valor',
                 'vamos',
                 'van',
                 'vaya',
                 'verdad',
                 'verdadera',
                 'verdadero',
                 'versus',
                 'vía',
                 'vosostras',
                 'vosostros',
                 'vosotras',
                 'vosotros',
                 'voy',
                 'vuestra',
                 'vuestras',
                 'vuestro',
                 'vuestros',
                 'vusco',
                 'y',
                 'ya',
                 'yo',
                 'optimizando',
                 'actualmente',
                 'llevar',
                 'manera',
                 'podrán',
                 'reduciendo',
                 'brindar'
    }

    text_es = request.json['text']
    stopwords_list = request.json['stopwords']
    stopwords_list_clean = re.sub('[\[\]]', '', stopwords_list).split(", ")
    stopwords.update(stopwords_list_clean)

    html = markdown.markdown(text_es)
    plain_text = html2text.html2text(html)
    plain_text = re.sub('[!@·•*\[\]/#$]', '', plain_text)
    plain_text = plain_text.replace('\\n', '. ')
    plain_text = re.sub(r'http\S+', '', plain_text, flags=re.MULTILINE)
    plain_text = re.sub(r'www\S+', '', plain_text, flags=re.MULTILINE)

    result = []

    # de 2 palabras
    rake = Rake(
        language_code='es',
        max_words=2,
        generated_stopwords_max_len=20,
        stopwords=stopwords
    )
    key_words_2 = rake.apply(plain_text)
    keys2 = key_words_2[:20]

    for key in keys2:
        result.append(key[0])

    # de 1 palabra
    rake = Rake(
        language_code='es',
        max_words=1,
        generated_stopwords_max_len=20,
        stopwords=stopwords
    )
    key_words_1 = rake.apply(plain_text)
    keys1 = key_words_1[:50]

    for key in keys1:
        if not stringResultContains(result, key[0]):
            if len(result) < 40:
                result.append(key[0])

    response = {
        "project_keywords": result
    }

    return response

def stringResultContains(result, word):
    for res in result:
        if word in res:
            return 1

def resultContains(result, word):
    for res in result:
        if word in res['name']:
            return 1


if __name__ == '__main__':
    port = int(os.environ.get('PORT', 8084))
    app.run(host='0.0.0.0', port=port)